In [19]:
import numpy as np
import pandas as pd
input_file_name = "../data_sets/lab1.xlsx"
output_file_name = "../data_sets/lab1_prepared.xlsx"

In [20]:
drop_columns = ["номер", "дата"]
df = pd.read_excel(input_file_name, sheet_name='VU')
header = df.columns.to_numpy()
df

c:\python\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,осредненные параметры,Unnamed: 5,Unnamed: 6,На конец режима,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,NaN,NaN,Глубина манометра,Dшт,Руст,Рзаб,Pлин,Руст,Рзаб,Рлин,...,Рпл. Тек (Карноухов),Pсб,Pсб,Ro_g,Ro_c,Ro_w,Удельная плотность газа,G_total,КГФ,КГФ
1,№,дд.мм.гггг,м,мм,бара,бара,бара,бар,бар,бар,...,МПа,атм,бар,кг/м3,кг/м3,кг/м3,б/р,кг/с,г/м3,т/тыс.м3
2,804,2008-06-05 00:00:00,3576.3,7.94,249.6,370.1,101.8,249,359.6,101.8,...,-,93.6,92.376018,0.806017,801,1000,0.669449,2.782623,311.9094,NaN
3,804,2008-06-06 00:00:00,3576.3,9.53,233.5,364.6,101.3,231,338.1,102.4,...,-,92.9,91.685171,0.806017,801,1000,0.669449,3.697781,288.6003,NaN
4,804,2008-06-07 00:00:00,3576.3,11.11,213.4,357.1,101.6,211,314.8,100.6,...,-,91.4,90.204787,0.806017,801,1000,0.669449,4.515073,248.7906,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,22505,2009-09-23 00:00:00,3678,12.7,182.2,271.586,93.255111,179,258.6,92.702141,...,60.8,89.7,88.527017,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,22505,2009-09-27 00:00:00,3678,14.29,157,249.076,96.472143,153,233.5,100.060417,...,60.8,87.3,86.158401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,22505,2010-04-09 00:00:00,3679.5,7.94,211.9,289.3877,91.131226,208,289.6,91.304642,...,61.3,88.2,87.046632,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,22505,2010-04-14 00:00:00,3679.5,9.53,204,282.8709,91.173008,201,275.3,91.616821,...,61.3,88.5,87.342709,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,22505,2010-04-17 00:00:00,3679.5,11.11,187.5,267.4787,91.530262,184,255,89.507935,...,61.3,89.8,88.625709,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# set new header (line 2)
df.iloc[0,0] = drop_columns[0]
df.iloc[0,1] = drop_columns[1]
df.columns = df.iloc[0]
df

,номер,дата,Глубина манометра,Dшт,Руст,Рзаб,Pлин,Руст,Рзаб,Рлин,...,Рпл. Тек (Карноухов),Pсб,Pсб,Ro_g,Ro_c,Ro_w,Удельная плотность газа,G_total,КГФ,КГФ
0,номер,дата,Глубина манометра,Dшт,Руст,Рзаб,Pлин,Руст,Рзаб,Рлин,...,Рпл. Тек (Карноухов),Pсб,Pсб,Ro_g,Ro_c,Ro_w,Удельная плотность газа,G_total,КГФ,КГФ
1,№,дд.мм.гггг,м,мм,бара,бара,бара,бар,бар,бар,...,МПа,атм,бар,кг/м3,кг/м3,кг/м3,б/р,кг/с,г/м3,т/тыс.м3
2,804,2008-06-05 00:00:00,3576.3,7.94,249.6,370.1,101.8,249,359.6,101.8,...,-,93.6,92.376018,0.806017,801,1000,0.669449,2.782623,311.9094,NaN
3,804,2008-06-06 00:00:00,3576.3,9.53,233.5,364.6,101.3,231,338.1,102.4,...,-,92.9,91.685171,0.806017,801,1000,0.669449,3.697781,288.6003,NaN
4,804,2008-06-07 00:00:00,3576.3,11.11,213.4,357.1,101.6,211,314.8,100.6,...,-,91.4,90.204787,0.806017,801,1000,0.669449,4.515073,248.7906,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,22505,2009-09-23 00:00:00,3678,12.7,182.2,271.586,93.255111,179,258.6,92.702141,...,60.8,89.7,88.527017,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,22505,2009-09-27 00:00:00,3678,14.29,157,249.076,96.472143,153,233.5,100.060417,...,60.8,87.3,86.158401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,22505,2010-04-09 00:00:00,3679.5,7.94,211.9,289.3877,91.131226,208,289.6,91.304642,...,61.3,88.2,87.046632,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,22505,2010-04-14 00:00:00,3679.5,9.53,204,282.8709,91.173008,201,275.3,91.616821,...,61.3,88.5,87.342709,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,22505,2010-04-17 00:00:00,3679.5,11.11,187.5,267.4787,91.530262,184,255,89.507935,...,61.3,89.8,88.625709,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# drop redurant rows
df.drop(0, inplace=True)
dim = df.drop(1, inplace=True)
df

,номер,дата,Глубина манометра,Dшт,Руст,Рзаб,Pлин,Руст,Рзаб,Рлин,...,Рпл. Тек (Карноухов),Pсб,Pсб,Ro_g,Ro_c,Ro_w,Удельная плотность газа,G_total,КГФ,КГФ
2,804,2008-06-05 00:00:00,3576.3,7.94,249.6,370.1,101.8,249,359.6,101.8,...,-,93.6,92.376018,0.806017,801,1000,0.669449,2.782623,311.9094,NaN
3,804,2008-06-06 00:00:00,3576.3,9.53,233.5,364.6,101.3,231,338.1,102.4,...,-,92.9,91.685171,0.806017,801,1000,0.669449,3.697781,288.6003,NaN
4,804,2008-06-07 00:00:00,3576.3,11.11,213.4,357.1,101.6,211,314.8,100.6,...,-,91.4,90.204787,0.806017,801,1000,0.669449,4.515073,248.7906,NaN
5,804,2008-06-08 00:00:00,3576.3,12.7,191.6,347.4,98.4,187,291.5,99,...,-,89.2,88.033555,0.806017,801,1000,0.669449,5.217673,223.5591,NaN
6,804,2008-06-09 00:00:00,3576.3,14.29,171.9,337.7,99.2,169,270.3,99.5,...,-,89.7,88.527017,0.806017,801,1000,0.669449,5.765092,215.1486,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,22505,2009-09-23 00:00:00,3678,12.7,182.2,271.586,93.255111,179,258.6,92.702141,...,60.8,89.7,88.527017,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,22505,2009-09-27 00:00:00,3678,14.29,157,249.076,96.472143,153,233.5,100.060417,...,60.8,87.3,86.158401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,22505,2010-04-09 00:00:00,3679.5,7.94,211.9,289.3877,91.131226,208,289.6,91.304642,...,61.3,88.2,87.046632,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,22505,2010-04-14 00:00:00,3679.5,9.53,204,282.8709,91.173008,201,275.3,91.616821,...,61.3,88.5,87.342709,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,22505,2010-04-17 00:00:00,3679.5,11.11,187.5,267.4787,91.530262,184,255,89.507935,...,61.3,89.8,88.625709,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df = df.reset_index(drop=True)
df

,номер,дата,Глубина манометра,Dшт,Руст,Рзаб,Pлин,Руст,Рзаб,Рлин,...,Рпл. Тек (Карноухов),Pсб,Pсб,Ro_g,Ro_c,Ro_w,Удельная плотность газа,G_total,КГФ,КГФ
0,804,2008-06-05 00:00:00,3576.3,7.94,249.6,370.1,101.8,249,359.6,101.8,...,-,93.6,92.376018,0.806017,801,1000,0.669449,2.782623,311.9094,NaN
1,804,2008-06-06 00:00:00,3576.3,9.53,233.5,364.6,101.3,231,338.1,102.4,...,-,92.9,91.685171,0.806017,801,1000,0.669449,3.697781,288.6003,NaN
2,804,2008-06-07 00:00:00,3576.3,11.11,213.4,357.1,101.6,211,314.8,100.6,...,-,91.4,90.204787,0.806017,801,1000,0.669449,4.515073,248.7906,NaN
3,804,2008-06-08 00:00:00,3576.3,12.7,191.6,347.4,98.4,187,291.5,99,...,-,89.2,88.033555,0.806017,801,1000,0.669449,5.217673,223.5591,NaN
4,804,2008-06-09 00:00:00,3576.3,14.29,171.9,337.7,99.2,169,270.3,99.5,...,-,89.7,88.527017,0.806017,801,1000,0.669449,5.765092,215.1486,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,22505,2009-09-23 00:00:00,3678,12.7,182.2,271.586,93.255111,179,258.6,92.702141,...,60.8,89.7,88.527017,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,22505,2009-09-27 00:00:00,3678,14.29,157,249.076,96.472143,153,233.5,100.060417,...,60.8,87.3,86.158401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,22505,2010-04-09 00:00:00,3679.5,7.94,211.9,289.3877,91.131226,208,289.6,91.304642,...,61.3,88.2,87.046632,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,22505,2010-04-14 00:00:00,3679.5,9.53,204,282.8709,91.173008,201,275.3,91.616821,...,61.3,88.5,87.342709,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,22505,2010-04-17 00:00:00,3679.5,11.11,187.5,267.4787,91.530262,184,255,89.507935,...,61.3,89.8,88.625709,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# replace all '-' on Nan
def replace_skip(string: str):
    if string == '-':
        return np.nan
    else:
        return string

filled_df = df.applymap(replace_skip)
filled_df

,номер,дата,Глубина манометра,Dшт,Руст,Рзаб,Pлин,Руст,Рзаб,Рлин,...,Рпл. Тек (Карноухов),Pсб,Pсб,Ro_g,Ro_c,Ro_w,Удельная плотность газа,G_total,КГФ,КГФ
0,804,2008-06-05,3576.3,7.94,249.6,370.1000,101.800000,249.0,359.6,101.800000,...,NaN,93.6,92.376018,0.806017,801.0,1000.0,0.669449,2.782623,311.9094,NaN
1,804,2008-06-06,3576.3,9.53,233.5,364.6000,101.300000,231.0,338.1,102.400000,...,NaN,92.9,91.685171,0.806017,801.0,1000.0,0.669449,3.697781,288.6003,NaN
2,804,2008-06-07,3576.3,11.11,213.4,357.1000,101.600000,211.0,314.8,100.600000,...,NaN,91.4,90.204787,0.806017,801.0,1000.0,0.669449,4.515073,248.7906,NaN
3,804,2008-06-08,3576.3,12.70,191.6,347.4000,98.400000,187.0,291.5,99.000000,...,NaN,89.2,88.033555,0.806017,801.0,1000.0,0.669449,5.217673,223.5591,NaN
4,804,2008-06-09,3576.3,14.29,171.9,337.7000,99.200000,169.0,270.3,99.500000,...,NaN,89.7,88.527017,0.806017,801.0,1000.0,0.669449,5.765092,215.1486,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,22505,2009-09-23,3678,12.70,182.2,271.5860,93.255111,179.0,258.6,92.702141,...,60.8,89.7,88.527017,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,22505,2009-09-27,3678,14.29,157.0,249.0760,96.472143,153.0,233.5,100.060417,...,60.8,87.3,86.158401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,22505,2010-04-09,3679.5,7.94,211.9,289.3877,91.131226,208.0,289.6,91.304642,...,61.3,88.2,87.046632,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,22505,2010-04-14,3679.5,9.53,204.0,282.8709,91.173008,201.0,275.3,91.616821,...,61.3,88.5,87.342709,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,22505,2010-04-17,3679.5,11.11,187.5,267.4787,91.530262,184.0,255.0,89.507935,...,61.3,89.8,88.625709,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**remove first 'КГФ' column**

In [25]:
# remove it with boolean mask
df = filled_df
mask = np.ones(df.shape[1], dtype=bool)
mask[len(mask)-2] = False

df = df.loc[:, mask]
df

,номер,дата,Глубина манометра,Dшт,Руст,Рзаб,Pлин,Руст,Рзаб,Рлин,...,Рпл. Тек (Расчет по КВД),Рпл. Тек (Карноухов),Pсб,Pсб,Ro_g,Ro_c,Ro_w,Удельная плотность газа,G_total,КГФ
0,804,2008-06-05,3576.3,7.94,249.6,370.1000,101.800000,249.0,359.6,101.800000,...,56.5,NaN,93.6,92.376018,0.806017,801.0,1000.0,0.669449,2.782623,NaN
1,804,2008-06-06,3576.3,9.53,233.5,364.6000,101.300000,231.0,338.1,102.400000,...,56.5,NaN,92.9,91.685171,0.806017,801.0,1000.0,0.669449,3.697781,NaN
2,804,2008-06-07,3576.3,11.11,213.4,357.1000,101.600000,211.0,314.8,100.600000,...,56.5,NaN,91.4,90.204787,0.806017,801.0,1000.0,0.669449,4.515073,NaN
3,804,2008-06-08,3576.3,12.70,191.6,347.4000,98.400000,187.0,291.5,99.000000,...,56.5,NaN,89.2,88.033555,0.806017,801.0,1000.0,0.669449,5.217673,NaN
4,804,2008-06-09,3576.3,14.29,171.9,337.7000,99.200000,169.0,270.3,99.500000,...,56.5,NaN,89.7,88.527017,0.806017,801.0,1000.0,0.669449,5.765092,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,22505,2009-09-23,3678,12.70,182.2,271.5860,93.255111,179.0,258.6,92.702141,...,60.9,60.8,89.7,88.527017,NaN,NaN,NaN,NaN,NaN,NaN
181,22505,2009-09-27,3678,14.29,157.0,249.0760,96.472143,153.0,233.5,100.060417,...,60.9,60.8,87.3,86.158401,NaN,NaN,NaN,NaN,NaN,NaN
182,22505,2010-04-09,3679.5,7.94,211.9,289.3877,91.131226,208.0,289.6,91.304642,...,64.1,61.3,88.2,87.046632,NaN,NaN,NaN,NaN,NaN,NaN
183,22505,2010-04-14,3679.5,9.53,204.0,282.8709,91.173008,201.0,275.3,91.616821,...,64.1,61.3,88.5,87.342709,NaN,NaN,NaN,NaN,NaN,NaN
184,22505,2010-04-17,3679.5,11.11,187.5,267.4787,91.530262,184.0,255.0,89.507935,...,64.1,61.3,89.8,88.625709,NaN,NaN,NaN,NaN,NaN,NaN

**remove rows where G_total and КГФ are nan**

In [26]:
classes = ['G_total', 'КГФ']
df = df[(df[classes[0]].notna()) | (df[classes[1]].notna())]
df = df.reset_index(drop=True)
df

,номер,дата,Глубина манометра,Dшт,Руст,Рзаб,Pлин,Руст,Рзаб,Рлин,...,Рпл. Тек (Расчет по КВД),Рпл. Тек (Карноухов),Pсб,Pсб,Ro_g,Ro_c,Ro_w,Удельная плотность газа,G_total,КГФ
0,804,2008-06-05,3576.3,7.94,249.600000,370.1,101.800000,249.0,359.6,101.800,...,56.5,NaN,93.6,92.376018,0.806017,801.0,1000.0,0.669449,2.782623,NaN
1,804,2008-06-06,3576.3,9.53,233.500000,364.6,101.300000,231.0,338.1,102.400,...,56.5,NaN,92.9,91.685171,0.806017,801.0,1000.0,0.669449,3.697781,NaN
2,804,2008-06-07,3576.3,11.11,213.400000,357.1,101.600000,211.0,314.8,100.600,...,56.5,NaN,91.4,90.204787,0.806017,801.0,1000.0,0.669449,4.515073,NaN
3,804,2008-06-08,3576.3,12.70,191.600000,347.4,98.400000,187.0,291.5,99.000,...,56.5,NaN,89.2,88.033555,0.806017,801.0,1000.0,0.669449,5.217673,NaN
4,804,2008-06-09,3576.3,14.29,171.900000,337.7,99.200000,169.0,270.3,99.500,...,56.5,NaN,89.7,88.527017,0.806017,801.0,1000.0,0.669449,5.765092,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,22503,2009-01-28,3284,12.70,215.000000,307.8,98.600000,215.0,308.1,97.200,...,40.5,41.6,94.4,93.165556,NaN,782.0,NaN,0.660000,NaN,0.153
89,22503,2009-02-01,3284,14.29,198.000000,293.6,98.500000,197.0,293.9,98.400,...,40.5,41.6,94.0,92.770787,NaN,782.0,NaN,0.660000,NaN,0.147
90,22503,2010-08-16,3288.6,7.94,231.229167,309.1,92.600000,230.0,307.1,92.700,...,NaN,NaN,89.9,88.724402,NaN,779.6,NaN,0.668000,NaN,0.182
91,22503,2010-08-20,3288.6,11.11,217.201681,293.9,93.100000,215.0,293.9,93.300,...,NaN,NaN,90.8,89.612633,NaN,779.6,NaN,0.668000,NaN,0.145
92,22503,2011-10-02,3289.8,9.53,199.000000,271.0,95.945951,199.0,272.3,94.637,...,39.9,NaN,94.0,92.770787,NaN,772.6,NaN,0.671000,NaN,0.139

**removing 'str' items**

In [27]:
#convert df to dict view
dict_df = df.to_dict(orient='list')
print(dict_df.keys())
print(dict_df["номер"])

dict_keys(['номер', 'дата', 'Глубина манометра', 'Dшт', 'Руст', 'Рзаб', 'Pлин', 'Рлин', 'Туст', 'Тна шлейфе', 'Тзаб', 'Tлин', 'Дебит газа', 'Дебит ст. конд.', 'Дебит воды', 'Дебит смеси', 'Дебит гааз', 'Дебит кон нестабильный', 'Нэф', 'Рпл. Тек (послед точка на КВД)', 'Рпл. Тек (Расчет по КВД)', 'Рпл. Тек (Карноухов)', 'Pсб', 'Ro_g', 'Ro_c', 'Ro_w', 'Удельная плотность газа ', 'G_total', 'КГФ'])
[804, 804, 804, 804, 804, 804, 807, 807, 807, 807, 807, 807, 807, 807, 807, 807, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 20503, 21002, 21002, 21002, 21002, 21002, 21002, 21002, 21002, 21002, 21002, 21002, 21203, 21203, 21203, 21303, 21303, 21303, 21303, 21303, 21303, 21303, 21303, 21303, 21303, 21303, 21303, 21303, 21303, 22501, 22501, 22501, 22501, 22501, 22501, 22501, 22501, 22501, 22501, 22501, 22501, 22501, 22501, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503, 22503]

C:\Users\Andrew\AppData\Local\Temp/ipykernel_4288/514905621.py:2: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  dict_df = df.to_dict(orient='list')

In [28]:
# remove 'str' items from dataframe dict
def fill_str(data):
    for i in range(len(data)):
        item = data[i]

        if type(item) == str:
            data[i] = np.nan


for key in dict_df:
    if key != drop_columns[0] and key != drop_columns[1]:
        fill_str(data=dict_df[key])

#save dict as dataframe back
df = pd.DataFrame.from_dict(dict_df)
df

,номер,дата,Глубина манометра,Dшт,Руст,Рзаб,Pлин,Рлин,Туст,Тна шлейфе,...,Рпл. Тек (послед точка на КВД),Рпл. Тек (Расчет по КВД),Рпл. Тек (Карноухов),Pсб,Ro_g,Ro_c,Ro_w,Удельная плотность газа,G_total,КГФ
0,804,2008-06-05,3576.3,7.94,249.0,359.6,101.800000,101.800,53.0,31.7,...,45.25,56.5,NaN,92.376018,0.806017,801.0,1000.0,0.669449,2.782623,NaN
1,804,2008-06-06,3576.3,9.53,231.0,338.1,101.300000,102.400,58.8,37.6,...,45.25,56.5,NaN,91.685171,0.806017,801.0,1000.0,0.669449,3.697781,NaN
2,804,2008-06-07,3576.3,11.11,211.0,314.8,101.600000,100.600,63.6,42.8,...,45.25,56.5,NaN,90.204787,0.806017,801.0,1000.0,0.669449,4.515073,NaN
3,804,2008-06-08,3576.3,12.70,187.0,291.5,98.400000,99.000,64.7,46.2,...,45.25,56.5,NaN,88.033555,0.806017,801.0,1000.0,0.669449,5.217673,NaN
4,804,2008-06-09,3576.3,14.29,169.0,270.3,99.200000,99.500,64.0,49.4,...,45.25,56.5,NaN,88.527017,0.806017,801.0,1000.0,0.669449,5.765092,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,22503,2009-01-28,3284.0,12.70,215.0,308.1,98.600000,97.200,65.0,45.8,...,35.28,40.5,41.6,93.165556,NaN,782.0,NaN,0.660000,NaN,0.153
89,22503,2009-02-01,3284.0,14.29,197.0,293.9,98.500000,98.400,66.9,49.8,...,35.28,40.5,41.6,92.770787,NaN,782.0,NaN,0.660000,NaN,0.147
90,22503,2010-08-16,3288.6,7.94,230.0,307.1,92.600000,92.700,51.0,NaN,...,33.21,NaN,NaN,88.724402,NaN,779.6,NaN,0.668000,NaN,0.182
91,22503,2010-08-20,3288.6,11.11,215.0,293.9,93.100000,93.300,60.0,NaN,...,33.21,NaN,NaN,89.612633,NaN,779.6,NaN,0.668000,NaN,0.145
92,22503,2011-10-02,3289.8,9.53,199.0,272.3,95.945951,94.637,56.0,NaN,...,NaN,39.9,NaN,92.770787,NaN,772.6,NaN,0.671000,NaN,0.139

**save prepared dataset**

In [29]:
df.to_excel(output_file_name, index=False)